version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
      - image: circleci/mysql:5.6
        environment:
          RAILS_ENV: test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          DB_HOST: 127.0.0.1

    working_directory: ~/g221_rails_training

    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - g221-rails-training-bundle-v2-{{ checksum "Gemfile.lock" }}
            - g221-rails-training-bundle-v2-

      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: Install dependencies
          command: |
            bundle check --path vendor/bundle || bundle install --jobs=4 --retry=3 --path vendor/bundle


      - save_cache:
          key: g221-rails-training-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Database setup
          command: |
            cp ./config/database.example.yml ./config/database.yml
            bundle exec rake db:create db:migrate db:seed

      - run:
          name: run rubocop
          command: bundle exec rubocop

      - run:
          name: Run rspec
          command: |
            bundle exec rspec --require spec_helper \
                              --color \
                              --format documentation \
                              spec

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
