api_errors:
  error_codes:
    standard_error: 500
    custom_error: 500
    record_invalid: 400
    record_not_found: 404
    unauthorized_error: 401

http_code:
  code_200: 200
  code_201: 201
  code_204: 204
  code_400: 400
  code_401: 401
  code_403: 403
  code_404: 404
  code_500: 500

auth_token:
  exp_time: <%= 1.hours.from_now %>
